import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useWeb3 } from "../components/Web3js";
import styles from "../styles/Home.module.css";
import State from "../../truffle/build/contracts/StateContract.json";
const Home: NextPage = () => {
  const { web3, selectedAccountAddress } = useWeb3();
  const [networkId, setnetworkId] = useState<number | undefined>(undefined);
  useEffect(() => {
    (async () => {
      setnetworkId(await web3?.eth.net.getId());
    })();
  }, [web3]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>networkId: {networkId}</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
