import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useWeb3 } from "../components/Web3js";
import styles from "../styles/Home.module.css";
import State from "../../truffle/build/contracts/StateContract.json";
const Home: NextPage = () => {
  const { web3 } = useWeb3();
  const [accounts, setaccounts] = useState<string[] | undefined>(undefined);
  const [networkId, setnetworkId] = useState<number | undefined>(undefined);
  useEffect(() => {
    (async () => {
      setaccounts(await web3?.eth.getAccounts());
      setnetworkId(await web3?.eth.net.getId());
    })();
  }, [web3]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {accounts?.map((acc) => {
            return <div key={acc}>{acc}</div>;
          })}
        </div>
        <div> {networkId}</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
